[package]
name = "reliquary-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf-codegen = "3.4.0"
serde_json = "1.0.114"